if (WIN32)
    set(XMRIG_OS_WIN ON)
elseif (APPLE)
    set(XMRIG_OS_APPLE ON)

    if (IOS OR CMAKE_SYSTEM_NAME STREQUAL iOS)
        set(XMRIG_OS_IOS ON)
    else()
        set(XMRIG_OS_MACOS ON)
    endif()
else()
    set(XMRIG_OS_UNIX ON)

    if (ANDROID OR CMAKE_SYSTEM_NAME MATCHES "Android")
        set(XMRIG_OS_ANDROID ON)
    elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
        set(XMRIG_OS_LINUX ON)
        if(EXISTS "/etc/alpine-release")
            set(XMRIG_OS_ALPINE ON)
        endif()
        if(WITH_ALPINE_MUSL OR XMRIG_OS_ALPINE)
            find_program(MUSL_GCC musl-gcc HINTS /usr/bin /usr/local/bin)
            if(MUSL_GCC)
                set(CMAKE_C_COMPILER "${MUSL_GCC}")
                set(CMAKE_CXX_COMPILER "${MUSL_GCC}")
                message(STATUS "Using musl-gcc for Alpine Linux build: ${MUSL_GCC}")
            endif()
        endif()
    elseif(CMAKE_SYSTEM_NAME STREQUAL FreeBSD OR CMAKE_SYSTEM_NAME STREQUAL DragonFly)
        set(XMRIG_OS_FREEBSD ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL OpenBSD)
        set(XMRIG_OS_OPENBSD ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Haiku")
        set(XMRIG_OS_HAIKU ON)
    endif()
endif()

if (XMRIG_OS_WIN)
    add_definitions(-DWIN32 -DXMRIG_OS_WIN)
elseif(XMRIG_OS_APPLE)
    add_definitions(-DXMRIG_OS_APPLE)

    if (XMRIG_OS_IOS)
        add_definitions(-DXMRIG_OS_IOS)
    else()
        add_definitions(-DXMRIG_OS_MACOS)
    endif()

    if (XMRIG_ARM)
        set(WITH_SECURE_JIT ON)
    endif()
elseif(XMRIG_OS_UNIX)
    add_definitions(-DXMRIG_OS_UNIX)

    if (XMRIG_OS_ANDROID)
        add_definitions(-DXMRIG_OS_ANDROID)
    elseif (XMRIG_OS_LINUX)
        add_definitions(-DXMRIG_OS_LINUX)
        if (XMRIG_OS_ALPINE)
            add_definitions(-DXMRIG_OS_ALPINE)
        endif()
    elseif (XMRIG_OS_FREEBSD)
        add_definitions(-DXMRIG_OS_FREEBSD)
    elseif (XMRIG_OS_OPENBSD)
        add_definitions(-DXMRIG_OS_OPENBSD)
    elseif (XMRIG_OS_HAIKU)
        add_definitions(-DXMRIG_OS_HAIKU)
    endif()
endif()

if (WITH_SECURE_JIT)
    add_definitions(-DXMRIG_SECURE_JIT)
endif()
